### ISSUE TITLE
Management master data using ehon.

### ISSUE THREAD

**Issue by Sixeight** [hekk/ehon#1]
I wanna use ehon to manage "master data" that is game item for example.

First, define clas that extends Ehon::Model,

``` ruby
class Item < Ehon::Model
end
```

then ehon load yaml file automatically.

``` yaml
item:
  1:
    name: "potion"
    value: 5
  2:
    name: "high potion"
    value: 10
```
